<?php

return array(
    'db' => array(
        'SQL' => array(
            'driver' => 'mysql',
            'dbname' => 'test',
            'username' => 'root',
            'password' => '123456',
            'host' => 'localhost',
            'port' => 3306,
            'tables' => array(
            'usuarios' => array(
              'nombre' => 'usuarios',
              'properties' => '(id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                nombre VARCHAR(49) NOT NULL,
                email VARCHAR(50),
                password VARCHAR(100) NOT NULL)',
              ),
            ),
        ),
        'JSON' => array(
            'offset' => 'usuarios',
            'file_path' => $_SERVER['DOCUMENT_ROOT'].'/usuarios.json',
        ),
    ),
    'model' => array(
        'URL' => array(
            'usuario' => $_SERVER['DOCUMENT_ROOT'].'/model/usuario.php',
        ),
        'URI' => array(
          'usuario' => '/model/usuario.php',
        ),
    ),
    'view' => array(
        'URL' => array(
            'index' => $_SERVER['DOCUMENT_ROOT'].'/index.php',
            'home' => $_SERVER['DOCUMENT_ROOT'].'/view/home.php',
            'faqs' => $_SERVER['DOCUMENT_ROOT'].'/view/faqs.php',
            'login' => $_SERVER['DOCUMENT_ROOT'].'/view/login.php',
            'menu' => $_SERVER['DOCUMENT_ROOT'].'/view/menu.php',
            'registrar' => $_SERVER['DOCUMENT_ROOT'].'/view/registrar.php',
            'footer' => $_SERVER['DOCUMENT_ROOT'].'/view/footer.php',
            'head' => $_SERVER['DOCUMENT_ROOT'].'/view/head.php',
            'style' => $_SERVER['DOCUMENT_ROOT'].'/css/style.css',
            'ajax' => $_SERVER['DOCUMENT_ROOT'].'/js/ajax.js',
            'faqs_script' => $_SERVER['DOCUMENT_ROOT'].'/js/faqs.js',
            'validacion' => $_SERVER['DOCUMENT_ROOT'].'/js/validacion.php',
        ),
        'URI' => array(
            'index' => '/index.php',
            'home' => '/view/home.php',
            'faqs' => '/view/faqs.php',
            'login' => '/view/login.php',
            'menu' => '/view/menu.php',
            'registrar' => '/view/registrar.php',
            'footer' => '/view/footer.php',
            'head' => '/view/head.php',
            'style' => '/css/style.css',
            'ajax' => '/js/ajax.js',
            'faqs_script' => '/js/faqs.js',
            'validacion' => '/js/validacion.php',
        ),
    ),
    'controller' => array(
        'URL' => array(
            'validationConfig' => $_SERVER['DOCUMENT_ROOT'].'/config/validation_config.php',
            'submit_user' => $_SERVER['DOCUMENT_ROOT'].'/controller/submit_user.php',
            'SQLServer' => $_SERVER['DOCUMENT_ROOT'].'/controller/SQL/SQLServer.php',
            'repositorio' => $_SERVER['DOCUMENT_ROOT'].'/controller/Repositories/repositorio.php',
            'repositorioGenerico' => $_SERVER['DOCUMENT_ROOT'].'/controller/Repositories/repositorioGenerico.php',
            'repositorioUsuarios' => $_SERVER['DOCUMENT_ROOT'].'/controller/Repositories/repositorioUsuarios.php',
            'repositorioJSON' => $_SERVER['DOCUMENT_ROOT'].'/controller/JSON/repositorioJSON.php',
            'repositorioUsuariosJSON' => $_SERVER['DOCUMENT_ROOT'].'/controller/JSON/repositorioUsuariosJSON.php',
            'repositorioGenericoJSON' => $_SERVER['DOCUMENT_ROOT'].'/controller/JSON/repositorioGenericoJSON.php',
            'repositorioSQL' => $_SERVER['DOCUMENT_ROOT'].'/controller/SQL/repositorioSQL.php',
            'repositorioGenericoSQL' => $_SERVER['DOCUMENT_ROOT'].'/controller/SQL/repositorioGenericoSQL.php',
            'repositorioUsuariosSQL' => $_SERVER['DOCUMENT_ROOT'].'/controller/SQL/repositorioUsuariosSQL.php',
            'validator' => $_SERVER['DOCUMENT_ROOT'].'/controller/Validation/validator.php',
            'auth' => $_SERVER['DOCUMENT_ROOT'].'/controller/Auth/auth.php',
            'login' => $_SERVER['DOCUMENT_ROOT'].'/controller/Auth/login.php',
            'userValidator' => $_SERVER['DOCUMENT_ROOT'].'/controller/Validation/userValidator.php',
            'signUpValidator' => $_SERVER['DOCUMENT_ROOT'].'/controller/Validation/signup-validator.php',
            'loginValidator' => $_SERVER['DOCUMENT_ROOT'].'/controller/Validation/loginValidator.php',
            'support' => $_SERVER['DOCUMENT_ROOT'].'/controller/Auth/support.php',
            'Config' => $_SERVER['DOCUMENT_ROOT'].'/controller/Configuration/Config.php',
        ),
        'URI' => array(
            'validationConfig' => '/config/validation_config.php',
            'submit_user' => '/controller/submit_user.php',
            'SQLConnection' => '/controller/SQL/SQLConnection.php',
            'repositorio' => '/controller/Repositories/repositorio.php',
            'repositorioGenerico' => '/controller/Repositories/repositorioGenerico.php',
            'repositorioUsuarios' => '/controller/Repositories/repositorioUsuarios.php',
            'repositorioSQL' => '/controller/SQL/repositorioSQL.php',
            'repositorioGenericoSQL' => '/controller/SQL/repositorioGenericoSQL.php',
            'repositorioUsuariosSQL' => '/controller/SQL/repositorioUsuariosSQL.php',
            'repositorioJSON' => '/controller/JSON/repositorioJSON.php',
            'repositorioGenericoJSON' => '/controller/JSON/repositorioGenericoJSON.php',
            'repositorioUsuariosJSON' => '/controller/JSON/repositorioUsuariosJSON.php',
            'validator' => '/controller/Validation/validator.php',
            'auth' => '/controller/Auth/auth.php',
            'login' => '/controller/Auth/login.php',
            'userValidator' => '/controller/Validation/userValidator.php',
            'signUpValidator' => '/controller/Validation/signup-validator.php',
            'loginValidator' => '/controller/Validation/loginValidator.php',
            'support' => '/controller/Auth/support.php',
            'Config' => '/controller/Configuration/Config.php',
        ),
    ),
);
